version: '3.8'

x-defaults: &default-env
  env_file:
    - .env
  environment:
    - DOMAIN=${DOMAIN}
    - CLIENT_ID=${CLIENT_ID}
    - CLIENT_SECRET=${CLIENT_SECRET}
    - VERIFY_SSL=${VERIFY_SSL}

services:
  frontend:
    <<: *default-env
    image: registry.gitlab.com/marc.haenni/semesterarbeit-3-marc-haenni/frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - file-service
      - license-service
      - redis
    restart: unless-stopped
    networks:
      - backend

  auth-service:
    <<: *default-env
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - FRONTEND_URL=https://${DOMAIN}/
      - REDIRECT_URI=https://${DOMAIN}/getAToken
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend

  file-service:
    <<: *default-env
    build: ./file-service
    ports:
      - "5002:5002"
    volumes:
      - ./file-service/uploaded_files:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend

  license-service:
    <<: *default-env
    build: ./license-service
    ports:
      - "5003:5003"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend

  redis:
    <<: *default-env
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

  ma-proxy:
    <<: *default-env
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: >
      /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/user_conf.d/nginx-proxy.prod.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - CERTBOT_EMAIL=marc.haenni@hotmail.ch
      - CERTBOT_DOMAINS=${DOMAIN}
      - DOMAIN=${DOMAIN}
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - frontend
      - auth-service
      - file-service
      - license-service
    networks:
      - backend

volumes:
  nginx_secrets:
  redis_data:

networks:
  backend:

